from pharmaB2B.customers.serializers.contact_us import ContactUsSerializer
from pharmaB2B.customers.serializers.faqs import FAQsSerializer
from pharmaB2B.customers.serializers.registration import RegistrationSerializer
