# Generated by Django 4.1.3 on 2022-12-17 17:36

from django.db import migrations
import pharmaB2B.core.managers.users


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', pharmaB2B.core.managers.users.CustomUserManager()),
            ],
        ),
    ]
