# Generated by Django 4.1.3 on 2023-01-09 11:14

from django.db import migrations, models
import pharmaB2B.utils


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='orders',
            name='expected_delivery_date',
            field=models.DateField(default=pharmaB2B.utils.get_delivery_date),
        ),
    ]
