# Generated by Django 4.1.3 on 2022-12-15 21:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('packaging_type', models.TextField()),
                ('units_per_package', models.IntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.manufacturers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='GB')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('received_quantity', models.IntegerField(default=0)),
                ('received_on', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('batch_number', models.TextField(unique=True)),
                ('purchase_unit_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('barcode_number', models.TextField(unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('batch_number', models.TextField()),
                ('status', models.TextField(choices=[('in-stock', 'in-stock'), ('booked', 'booked'), ('sold', 'sold'), ('breakage', 'breakage'), ('expired', 'expired')], default='in-stock')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stocks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
