# Generated by Django 4.1.3 on 2023-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productstocks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='generic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
