
ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_PLACED = "placed"
ORDER_STATUS_PROCESSING = "processing"
ORDER_STATUS_SHIPPED = "shipped"
ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_CANCELLED = "cancelled"

ORDER_STATUSES = (
    (ORDER_STATUS_PENDING, ORDER_STATUS_PENDING),
    (ORDER_STATUS_PLACED, ORDER_STATUS_PLACED),
    (ORDER_STATUS_PROCESSING, ORDER_STATUS_PROCESSING),
    (ORDER_STATUS_SHIPPED, ORDER_STATUS_SHIPPED),
    (ORDER_STATUS_COMPLETED, ORDER_STATUS_COMPLETED),
    (ORDER_STATUS_CANCELLED, ORDER_STATUS_CANCELLED)
)

PACKAGE_STATUS_IN_STOCK = "in-stock"
PACKAGE_STATUS_BOOKED = "booked"
PACKAGE_STATUS_BREAKAGE = "breakage"
PACKAGE_STATUS_SOLD = "sold"
PACKAGE_STATUS_EXPIRED = "expired"

PACKAGE_STATUS = (
    (PACKAGE_STATUS_IN_STOCK, PACKAGE_STATUS_IN_STOCK),
    (PACKAGE_STATUS_BOOKED, PACKAGE_STATUS_BOOKED),
    (PACKAGE_STATUS_SOLD, PACKAGE_STATUS_SOLD),
    (PACKAGE_STATUS_BREAKAGE, PACKAGE_STATUS_BREAKAGE),
    (PACKAGE_STATUS_EXPIRED, PACKAGE_STATUS_EXPIRED),
)
