# Generated by Django 4.1.3 on 2022-12-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailers',
            name='verified_on',
            field=models.DateTimeField(null=True),
        ),
    ]
