# Generated by Django 4.1.3 on 2022-12-24 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_remove_retailers_verified_retailers_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailers',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
