# Generated by Django 4.1.3 on 2022-12-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_retailers_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailers',
            name='rejection_reason',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='retailers',
            name='status',
            field=models.TextField(choices=[('not-decided', 'not-decided'), ('verified', 'verified'), ('rejected', 'rejected')], default='not-decided'),
        ),
    ]
