# Generated by Django 4.1.3 on 2022-12-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_contactus_alter_faqs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contacted Us'},
        ),
    ]
