# Generated by Django 4.1.3 on 2023-01-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailers',
            options={'verbose_name': 'Retailer', 'verbose_name_plural': 'Retailers'},
        ),
    ]
